In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

In [3]:
X,y = make_classification(n_samples = 1000,n_features = 10 , n_classes = 2)

In [4]:
data = pd.DataFrame(X)

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(data,y,test_size = 0.3)

In [29]:
from sklearn.multiclass import OneVsRestClassifier


In [37]:
from sklearn.linear_model import LogisticRegression
base_model = LogisticRegression(max_iter=1000, random_state=42)
tuned_model = OneVsRestClassifier(base_model)

In [63]:
tuned_model.fit(X_train,y_train)
y_pred = tuned_model.predict(X_test)
tuned_model.predict_proba(X_test)[0]

array([0.71642903, 0.28357097])

In [65]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
score = accuracy_score(y_test , y_pred)
print("accuracy score is", score)
cm = confusion_matrix(y_test , y_pred)
print("confusion matrix"'\n', cm )

accuracy score is 0.89
confusion matrix
 [[133  17]
 [ 16 134]]


In [67]:
report = classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.89      0.89      0.89       150
           1       0.89      0.89      0.89       150

    accuracy                           0.89       300
   macro avg       0.89      0.89      0.89       300
weighted avg       0.89      0.89      0.89       300



In [61]:
test = X_test.iloc[10,:]

In [73]:
tuned_model.predict([test])

array([0])