In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
from sklearn.datasets import make_classification

In [4]:
X,y = make_classification(n_samples = 1000,n_features = 10 , n_classes = 2)

In [5]:
# no need for scaling already scaled data

In [6]:
data = pd.DataFrame(X)

In [7]:
display(data,type(y))

0         1         2         3         4         5         6  \
0    0.390233 -0.695186  0.263592 -0.611205 -1.054982 -0.463443  1.991602   
1    0.348177  0.046668  0.400620  0.546182  0.498849 -1.361500 -1.586774   
2   -0.409268 -0.807870 -0.193953 -1.180077 -0.099430 -1.110684  1.717460   
3    0.559704  1.009745 -0.880995 -1.196050 -1.912641  1.995554 -1.512932   
4    0.216139 -0.723829 -0.919839 -0.835778 -0.115219 -1.487077  1.025501   
..        ...       ...       ...       ...       ...       ...       ...   
995  2.060608  0.623632  0.657980 -0.602727 -0.222009  2.900634  0.806175   
996 -0.047530  0.170173  1.191260  0.007804 -0.506677 -0.593315 -1.224968   
997  1.301370  0.307433  0.863437 -0.062180 -0.187925 -1.254213 -2.403265   
998  0.992558  0.451151 -1.428862  0.138129  1.285392  0.740645 -0.833491   
999  0.698293  0.460640  0.318662 -0.381686 -2.132013  0.798383 -0.807030   

            7         8         9  
0    0.485629 -0.793132 -1.193167  
1    0.362524  0.911878  1.589282  
2    0.116520 -0.157915 -0.766556  
3    0.437643  1.259281  0.299942  
4    0.234950  1.051586 -0.153698  
..        ...       ...       ...  
995  0.445288 -0.460536 -1.622543  
996 -2.065172 -1.282658  1.057996  
997  0.090028 -0.201493  2.108961  
998 -1.221145  0.796111  0.297613  
999 -0.499274 -0.424813  0.258183  

[1000 rows x 10 columns]

numpy.ndarray

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test = train_test_split(data,y,test_size = 0.3)

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
model = LogisticRegression() # c is 1/lambda of ridge lasso parameter 

In [12]:
model.fit(X_train,y_train)

LogisticRegression()

In [13]:
y_pred = model.predict(X_test)

In [14]:
y_pred

array([0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0])

In [15]:
# prediciton probabiliy 
model.predict_proba(X_test)[0]

array([0.85681228, 0.14318772])

In [16]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [17]:
score = accuracy_score(y_test , y_pred)
print("accuracy score is", score)

accuracy score is 0.9133333333333333


In [18]:
cm = confusion_matrix(y_test , y_pred)
print("confusion matrix"'\n', cm )

confusion matrix
 [[143  13]
 [ 13 131]]


In [19]:
report = classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.92      0.92      0.92       156
           1       0.91      0.91      0.91       144

    accuracy                           0.91       300
   macro avg       0.91      0.91      0.91       300
weighted avg       0.91      0.91      0.91       300



# Hyper parameter tuning using Grid Search CV

In [21]:
tuned_model = LogisticRegression()

In [22]:
# adding all possible values of parameter in the grid for tuned_model

In [23]:
# Fix 1: Increase max_iter to stop ConvergenceWarnings
tuned_model = LogisticRegression(max_iter=10000, random_state=42)

# Fix 2: Use a list of dictionaries to map valid penalties to valid solvers
params = [
    # Config 1: l1 penalty (supported by liblinear and saga)
    {
        'penalty': ['l1'],
        'solver': ['liblinear', 'saga'],
        'C': [0.1, 1, 10, 100, 0.01]
    },
    
    # Config 2: l2 penalty (supported by all solvers)
    {
        'penalty': ['l2'],
        'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
        'C': [0.1, 1, 10, 100, 0.01]
    },
    
    # Config 3: elasticnet (only supported by saga, and requires l1_ratio)
    {
        'penalty': ['elasticnet'],
        'solver': ['saga'],
        'C': [0.1, 1, 10, 100, 0.01],
        'l1_ratio': [0.5] # elasticnet needs this parameter (0.5 = 50% l1, 50% l2)
    }
]

# Now run GridSearchCV with these corrected params
from sklearn.model_selection import StratifiedKFold, GridSearchCV
cv = StratifiedKFold(n_splits=5)

grid = GridSearchCV(tuned_model, param_grid=params, n_jobs=-1, scoring='accuracy', cv=cv)
grid.fit(X_train, y_train)


GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(max_iter=10000, random_state=42),
             n_jobs=-1,
             param_grid=[{'C': [0.1, 1, 10, 100, 0.01], 'penalty': ['l1'],
                          'solver': ['liblinear', 'saga']},
                         {'C': [0.1, 1, 10, 100, 0.01], 'penalty': ['l2'],
                          'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                     'saga']},
                         {'C': [0.1, 1, 10, 100, 0.01], 'l1_ratio': [0.5],
                          'penalty': ['elasticnet'], 'solver': ['saga']}],
             scoring='accuracy')

In [24]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(max_iter=10000, random_state=42),
             n_jobs=-1,
             param_grid=[{'C': [0.1, 1, 10, 100, 0.01], 'penalty': ['l1'],
                          'solver': ['liblinear', 'saga']},
                         {'C': [0.1, 1, 10, 100, 0.01], 'penalty': ['l2'],
                          'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                     'saga']},
                         {'C': [0.1, 1, 10, 100, 0.01], 'l1_ratio': [0.5],
                          'penalty': ['elasticnet'], 'solver': ['saga']}],
             scoring='accuracy')

In [26]:
grid.fit(X_train,y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(max_iter=10000, random_state=42),
             n_jobs=-1,
             param_grid=[{'C': [0.1, 1, 10, 100, 0.01], 'penalty': ['l1'],
                          'solver': ['liblinear', 'saga']},
                         {'C': [0.1, 1, 10, 100, 0.01], 'penalty': ['l2'],
                          'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                     'saga']},
                         {'C': [0.1, 1, 10, 100, 0.01], 'l1_ratio': [0.5],
                          'penalty': ['elasticnet'], 'solver': ['saga']}],
             scoring='accuracy')

In [27]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'saga'}

In [28]:
grid.best_score_

np.float64(0.9185714285714285)

In [29]:
y_pred1 = grid.predict(X_test)

In [30]:
score = accuracy_score(y_test , y_pred1)
print("accuracy score is", score)

accuracy score is 0.9266666666666666


In [31]:
cm = confusion_matrix(y_test , y_pred1)
print("confusion matrix"'\n', cm )

confusion matrix
 [[144  12]
 [ 10 134]]


In [32]:
report = classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.92      0.92      0.92       156
           1       0.91      0.91      0.91       144

    accuracy                           0.91       300
   macro avg       0.91      0.91      0.91       300
weighted avg       0.91      0.91      0.91       300



In [33]:
# Randomized search cv

In [34]:
from sklearn.model_selection import RandomizedSearchCV
random = RandomizedSearchCV(tuned_model,param_distributions = params , cv = 5, n_jobs = -1 , scoring = 'accuracy')

In [35]:
random.fit(X_train,y_train)

RandomizedSearchCV(cv=5,
                   estimator=LogisticRegression(max_iter=10000,
                                                random_state=42),
                   n_jobs=-1,
                   param_distributions=[{'C': [0.1, 1, 10, 100, 0.01],
                                         'penalty': ['l1'],
                                         'solver': ['liblinear', 'saga']},
                                        {'C': [0.1, 1, 10, 100, 0.01],
                                         'penalty': ['l2'],
                                         'solver': ['newton-cg', 'lbfgs',
                                                    'liblinear', 'sag',
                                                    'saga']},
                                        {'C': [0.1, 1, 10, 100, 0.01],
                                         'l1_ratio': [0.5],
                                         'penalty': ['elasticnet'],
                                         'solver': ['saga']}],
                   scoring='accuracy')

In [36]:
random.best_estimator_

LogisticRegression(C=0.1, max_iter=10000, penalty='l1', random_state=42,
                   solver='saga')

In [37]:
random.best_params_

{'solver': 'saga', 'penalty': 'l1', 'C': 0.1}

In [38]:
random.best_score_

np.float64(0.9185714285714285)

In [39]:
y_pred2 = random.predict(X_test)
score = accuracy_score(y_test , y_pred2)
print("accuracy score is", score)

accuracy score is 0.9266666666666666


In [40]:
cm = confusion_matrix(y_test , y_pred1)
print("confusion matrix"'\n', cm )

confusion matrix
 [[144  12]
 [ 10 134]]


In [41]:
report = classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.92      0.92      0.92       156
           1       0.91      0.91      0.91       144

    accuracy                           0.91       300
   macro avg       0.91      0.91      0.91       300
weighted avg       0.91      0.91      0.91       300

